language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r pip_requirements_readthedocs.txt
  - pip install -r pip_requirements_tests.txt
  - travis_retry pip install coveralls
# command to run tests
script:
  - set -e
  - python --version
  - python -m pytest -vv -k --disable-pytest-warnings --cov-config=.coveragerc --cov-report xml:coverage.xml --cov=asammdf/ test/
  - python -m sphinx -nW -b html documentation documentation/_build/html

after_success:
  - coveralls
