language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r doc/requirements.txt
  - pip install -r test/requirements.txt
  - travis_retry pip install coveralls
# command to run tests
script:
  - set -e
  - python --version
  - python -m coverage run --source=asammdf --omit="asammdf/gui/*" test/run_all.py
  - python -m coverage xml
  - python -m sphinx -nW -b html doc doc/_build/html

after_success:
  - coveralls
