name: Quick Tests

on:
  push:
  pull_request:
    branches:
      - 'development'

jobs:
  quick_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov
        pip install wheel numpy lz4 canmatrix pandas numexpr cChardet==2.1.5 natsort
        
    - name: Test with pytest
      run: |
        pytest test --color=yes --disable-pytest-warnings -vv -x